#!/usr/bin/env bash
set -euo pipefail

PORTAINER_AGENT_PORT=${PORTAINER_AGENT_PORT:-10000}
PORTAINER_HTTP_PORT=${PORTAINER_HTTP_PORT:-10001} # forwardPorts対象
LOCALSTACK_GATEWAY_PORT=${LOCALSTACK_GATEWAY_PORT:-10005} # forwardPorts対象
LOCALSTACK_SERVICE_PORT_START=${LOCALSTACK_SERVICE_PORT_START:-10006}
LOCALSTACK_SERVICE_PORT_END=${LOCALSTACK_SERVICE_PORT_END:-10056}
LOCALSTACK_VOLUME_PATH=${LOCALSTACK_VOLUME_PATH:-/home/node/.cache/localstack}

mkdir -p "${LOCALSTACK_VOLUME_PATH}"

export PORTAINER_AGENT_PORT
export PORTAINER_HTTP_PORT
export LOCALSTACK_GATEWAY_PORT
export LOCALSTACK_SERVICE_PORT_START
export LOCALSTACK_SERVICE_PORT_END
export LOCALSTACK_VOLUME_PATH

docker compose -f ".devcontainer/docker-compose.yml" up -d